### ISSUE TITLE
Cura 3.4.1 crashes

### ISSUE THREAD

**Issue by varazir** [fieldOfView/Cura-SimpleShapes#1]
Hello, 

When I try to add a cylinder or sphere Cura crashes. 
Cube works fine,

**Comment by fieldOfView** [comment]
This plugin is a work-in-progress. Thanks for trying it out though. Did you just happen upon it, or are you looking for something specific?

**Comment by varazir** [comment]
That it's OK, just liked to repport it :) 

I was just searching for cura-plugins on github and found this. I thought I could use it for custom mesh settings. Standard is blocks I was hoping I could use cylinder and spheres.

**Comment by flowchartsman** [comment]
Yeah, it would be super great if you could fix this. It's a great idea for a plugin to drop in modification meshes for infill and supports and such.

**Comment by fieldOfView** [comment]
I have updated the plugin to work with Cura 3.5 and newer.
